# Generated by Django 3.1 on 2020-08-19 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allowed_areas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shop',
            new_name='Allowed_areas',
        ),
    ]
